/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddProjectModal: typeof import('./components/AddProjectModal.vue')['default']
    BaseModal: typeof import('./components/BaseModal.vue')['default']
    CanvasGraph: typeof import('./components/graph/CanvasGraph.vue')['default']
    ChannelIcon: typeof import('./components/ChannelIcon.vue')['default']
    DiagramRenderer: typeof import('./components/diagram/DiagramRenderer.vue')['default']
    FilePickerPanel: typeof import('./components/FilePickerPanel.vue')['default']
    FlowChartSVG: typeof import('./components/diagram/FlowChartSVG.vue')['default']
    HandoffAttachment: typeof import('./components/HandoffAttachment.vue')['default']
    KnowledgeGraph: typeof import('./components/graph/KnowledgeGraph.vue')['default']
    MermaidChart: typeof import('./components/diagram/MermaidChart.vue')['default']
    MessageAnchorRail: typeof import('./components/MessageAnchorRail.vue')['default']
    NodeDetailDrawer: typeof import('./components/graph/NodeDetailDrawer.vue')['default']
    Onboarding: typeof import('./components/Onboarding.vue')['default']
    QuoteComposer: typeof import('./components/QuoteComposer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SandboxModeChip: typeof import('./components/SandboxModeChip.vue')['default']
    SelectionActionBar: typeof import('./components/SelectionActionBar.vue')['default']
    SessionMetricsLine: typeof import('./components/SessionMetricsLine.vue')['default']
    SessionSearchPanel: typeof import('./components/SessionSearchPanel.vue')['default']
    SessionSidebar: typeof import('./components/SessionSidebar.vue')['default']
    ThinkingTimeline: typeof import('./components/ThinkingTimeline.vue')['default']
  }
}
